name: p311
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ampl-asl=1.0.0=h5888daf_2
  - aom=3.12.1=h7934f7d_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - contourpy=1.3.3=py311hdb19cb5_0
  - cuda-crt-tools=12.8.93=h06a4308_3
  - cuda-cudart=12.8.90=hbdd6827_0
  - cuda-cudart_linux-64=12.8.90=hd1a145a_0
  - cuda-cupti=12.8.90=hbdd6827_1
  - cuda-nvcc-tools=12.8.93=hbdd6827_3
  - cuda-nvrtc=12.8.93=hbdd6827_1
  - cuda-nvtx=12.8.90=hbdd6827_1
  - cuda-nvvm-tools=12.8.93=hbdd6827_3
  - cuda-version=12.8=h30beaf8_3
  - cudnn=9.15.1.9=h4a770f4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyipopt=1.6.1=py311h63c440d_1
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dav1d=1.2.1=h5eee18b_0
  - double-conversion=3.1.5=he6710b0_1
  - expat=2.7.3=h3385a95_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.60.1=py311hee96239_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gettext=0.21.0=hedfda30_2
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - ipopt=3.14.19=h0804adb_0
  - jansson=2.14=h5eee18b_1
  - jpeg=9f=h5ce9db8_0
  - jsoncpp=1.9.4=hdb19cb5_3
  - kiwisolver=1.4.9=py311h24d9097_0
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libavif=1.3.0=h3539ee5_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=13_h8e06fc2_netlib
  - libcublas=12.8.4.1=hbdd6827_1
  - libcudnn=9.15.1.9=ha36b8be_0
  - libcudnn-dev=9.15.1.9=h1079e53_0
  - libcufft=11.3.3.83=hbdd6827_1
  - libcups=2.4.2=h252cb56_2
  - libcurand=10.3.9.90=hbdd6827_1
  - libcurl=8.16.0=heebcbe5_0
  - libcusolver=11.7.3.90=hbdd6827_1
  - libcusparse=12.5.8.93=hbdd6827_1
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.4=h77a78f3_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h4751f2c_7
  - libgrpc=1.62.2=h2d74bed_0
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libkrb5=1.21.3=h520c7b4_4
  - liblapack=3.9.0=13_h8876d29_netlib
  - libllvm15=15.0.7=he89c38a_4
  - libnghttp2=1.67.1=h697f920_0
  - libnsl=2.0.0=h5eee18b_0
  - libnvjitlink=12.8.93=hbdd6827_1
  - libopengl=1.7.0=h5eee18b_2
  - libopenjpeg=2.5.4=hee96239_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.50=h2ed474d_0
  - libpq=17.6=ha51bf15_0
  - libprotobuf=4.25.3=he621ea3_0
  - libscotch=7.0.5=h3428b0d_3
  - libsodium=1.0.20=heac8642_0
  - libspral=2025.05.20=hfabd9d1_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.1=h029b1ac_0
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.10.6=py311h06a4308_1
  - matplotlib-base=3.10.6=py311h71dd3da_1
  - mesalib=25.1.5=h31e3550_0
  - metis=5.1.0=hd0bcaf9_1007
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_2
  - mkl_fft=1.3.11=py311h5eee18b_0
  - mkl_random=1.2.8=py311ha02d727_0
  - ml_dtypes=0.5.4=py311h23c847b_0
  - mumps-include=5.7.3=ha770c72_5
  - mumps-seq=5.7.3=hcd84eb1_5
  - mysql-common=9.3.0=h0021b1a_3
  - mysql-libs=9.3.0=h797a5cd_3
  - nccl=2.28.9.1=h7b78073_0
  - ncurses=6.5=h7934f7d_0
  - numpy=2.0.1=py311h08b1b3b_1
  - numpy-base=2.0.1=py311hf175353_1
  - openldap=2.6.10=he9288cc_1
  - openssl=3.6.0=h26f9b46_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=25.0=py311h06a4308_1
  - pcre2=10.46=hf426167_0
  - pillow=12.0.0=py311h3b88751_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyparsing=3.2.5=py311h06a4308_0
  - pyqt=6.9.1=py311hc79087c_0
  - pyqt6-sip=13.10.2=py311hee96239_0
  - python=3.11.14=h6fa692b_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python_abi=3.11=2_cp311
  - qtbase=6.9.2=hd13baf8_5
  - qtdeclarative=6.9.2=h55666de_1
  - qtsvg=6.9.2=h75a08ff_1
  - qttools=6.9.2=hc856bc8_1
  - qtwayland=6.9.2=h9f1b7ec_1
  - qtwebchannel=6.9.2=hbdd6827_1
  - qtwebsockets=6.9.2=hbdd6827_1
  - re2=2022.04.01=h295c915_0
  - readline=8.3=hc2a1206_0
  - scipy=1.16.3=py311h1e13796_1
  - setuptools=80.9.0=py311h06a4308_0
  - sip=6.12.0=py311h7934f7d_0
  - six=1.17.0=py311h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.51.0=h2a70700_0
  - tbb=2021.13.0=h8d10470_4
  - tbb-devel=2021.13.0=h74b38a2_4
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py311h5eee18b_0
  - tzdata=2025b=h04d1e81_0
  - wayland=1.24.0=hdac8c69_0
  - wheel=0.45.1=py311h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - jax==0.8.1
      - jax-cuda12-pjrt==0.8.1
      - jax-cuda12-plugin==0.8.1
      - jaxlib==0.8.1
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-cupti-cu12==12.9.79
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.9.86
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu12==9.16.0.29
      - nvidia-cufft-cu12==11.4.1.4
      - nvidia-cusolver-cu12==11.7.5.82
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-nccl-cu12==2.28.9
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvshmem-cu12==3.4.5
prefix: /home/hofmann/miniconda3/envs/p311
